cleaned

diff --git a/awmtt b/awmtt
--- a/awmtt
+++ b/awmtt
@@ -4,7 +4,7 @@
 
 #{{{ Usage
 usage() {
-    cat <<EOF
+	cat <<EOF
 awmtt start [-B <path>] [-C <path>] [-D <int>] [-S <size>] [-a <opt>]... [-x <opts>]
 awmtt (stop [all] | restart)
 awmtt run [-D <int>] <command>
@@ -38,7 +38,7 @@ Examples:
   awmtt start -C /etc/xdg/awesome/rc.lua -D 3 -S 1280x800
   awmtt theme set zenburn -N
 EOF
-    exit 0
+	exit 0
 }
 [ "$#" -lt 1 ] && usage
 #}}}
@@ -46,7 +46,10 @@ EOF
 #{{{ Utilities
 awesome_pid() { pgrep -n "awesome"; }
 xephyr_pid() { pgrep -f xephyr_$D; }
-errorout() { echo "error: $*" >&2; exit 1; }
+errorout() {
+	echo "error: $*" >&2
+	exit 1
+}
 #}}}
 
 #{{{ Executable check
@@ -64,9 +67,9 @@ AWESOME_OPTIONS=""
 XEPHYR_OPTIONS=""
 # Path to rc.lua
 if [[ "$XDG_CONFIG_HOME" ]]; then
-    RC_FILE="$XDG_CONFIG_HOME"/awesome/rc.lua.test
+	RC_FILE="$XDG_CONFIG_HOME"/awesome/rc.lua.test
 else
-    RC_FILE="$HOME"/.config/awesome/rc.lua.test
+	RC_FILE="$HOME"/.config/awesome/rc.lua.test
 fi
 [[ ! -f "$RC_FILE" ]] && RC_FILE="$HOME"/.config/awesome/rc.lua
 #}}}
@@ -74,169 +77,188 @@ fi
 #{{{ Hostname Check - this is probably only useful for me. I have the same rc.lua running on two different machines
 HOSTNAME=$(uname -n)
 #}}}
-        
+
 #{{{ Functions
 #{{{ Start function
 start() {
-    # check for free $DISPLAYs
-    for ((i=0;;i++)); do
-        if [[ ! -f "/tmp/.X${i}-lock" ]]; then
-            D=$i;
-            break;
-        fi;
-    done
-    
-    "$XEPHYR" :$D -name xephyr_$D -ac -br -noreset -screen "$SIZE" $XEPHYR_OPTIONS >/dev/null 2>&1 &
-    sleep 1
-    DISPLAY=:$D.0 "$AWESOME" -c "$RC_FILE" $AWESOME_OPTIONS &
-    sleep 1
-    
-    # print some useful info
-    if [[ "$RC_FILE" =~ .test$ ]]; then
-    echo "Using a test file ($RC_FILE)"
-    else
-    echo "Caution: NOT using a test file ($RC_FILE)"
-    fi
+	# check for free $DISPLAYs
+	for ((i = 0; ; i++)); do
+		if [[ ! -f "/tmp/.X${i}-lock" ]]; then
+			D=$i
+			break
+		fi
+	done
 
-    echo "Display: $D, Awesome PID: $(awesome_pid), Xephyr PID: $(xephyr_pid)"
+	"$XEPHYR" :$D -name xephyr_$D -ac -br -noreset -screen "$SIZE" $XEPHYR_OPTIONS >/dev/null 2>&1 &
+	sleep 1
+	DISPLAY=:$D.0 "$AWESOME" -c "$RC_FILE" $AWESOME_OPTIONS &
+	sleep 1
+
+	# print some useful info
+	if [[ "$RC_FILE" =~ .test$ ]]; then
+		echo "Using a test file ($RC_FILE)"
+	else
+		echo "Caution: NOT using a test file ($RC_FILE)"
+	fi
+
+	echo "Display: $D, Awesome PID: $(awesome_pid), Xephyr PID: $(xephyr_pid)"
 }
 #}}}
 #{{{ Stop function
 stop() {
-    if [[ "$1" == all ]]; then
-        echo "Stopping all instances of Xephyr"
-        kill $(pgrep Xephyr) >/dev/null 2>&1
-    elif [[ $(xephyr_pid) ]]; then
-        echo "Stopping Xephyr for display $D"
-        kill $(xephyr_pid)
-    else
-        echo "Xephyr is not running or you did not specify the correct display with -D"
-        exit 0
-    fi
+	if [[ "$1" == all ]]; then
+		echo "Stopping all instances of Xephyr"
+		kill $(pgrep Xephyr) >/dev/null 2>&1
+	elif [[ $(xephyr_pid) ]]; then
+		echo "Stopping Xephyr for display $D"
+		kill $(xephyr_pid)
+	else
+		echo "Xephyr is not running or you did not specify the correct display with -D"
+		exit 0
+	fi
 }
 #}}}
 #{{{ Restart function
 restart() {
- 
-    echo -n "Restarting Awesome... "
-    for i in $(pgrep -f "awesome -c"); do
-        kill -s SIGHUP $i;
-    done
+
+	echo -n "Restarting Awesome... "
+	for i in $(pgrep -f "awesome -c"); do
+		kill -s SIGHUP $i
+	done
 }
 #}}}
 #{{{ Run function
 run() {
-    [[ -z "$D" ]] && D=1
-    DISPLAY=:$D.0 "$@" &
-    LASTPID=$!
-    echo "PID is $LASTPID"
+	[[ -z "$D" ]] && D=1
+	DISPLAY=:$D.0 "$@" &
+	LASTPID=$!
+	echo "PID is $LASTPID"
 }
 #}}}
 #{{{ Theme function
 theme() {
-    # List themes
-    theme_list() { 
-        if [[ -d $(dirname "$RC_FILE")/themes ]]; then
-            ls /usr/share/awesome/themes $(dirname "$RC_FILE")/themes
-        else
-            ls /usr/share/awesome/themes "$HOME"/.config/awesome/themes
-        fi
-    }    
-    case "$1" in
-        l|list) theme_list
-                exit 0
-                ;;
-    esac
-    
-    # Check for Beautiful library
-    BEAUTIFUL=$(grep -c 'beautiful.init' "$RC_FILE")
-    [[ "$BEAUTIFUL" -ge 1 ]] || errorout 'Could not detect theme library "beautiful". Exiting.'
+	# List themes
+	theme_list() {
+		if [[ -d $(dirname "$RC_FILE")/themes ]]; then
+			ls /usr/share/awesome/themes $(dirname "$RC_FILE")/themes
+		else
+			ls /usr/share/awesome/themes "$HOME"/.config/awesome/themes
+		fi
+	}
+	case "$1" in
+	l | list)
+		theme_list
+		exit 0
+		;;
+	esac
 
-    if [[ "$HOSTNAME" == laptop ]]; then
-        curtheme=$(grep "^themelap" "$RC_FILE" | awk -F\/ '{print $2}')
-    elif [[ "$HOSTNAME" == htpc ]]; then
-        curtheme=$(grep "^themehtpc" "$RC_FILE" | awk -F\/ '{print $2}')
-    else
-        curtheme=$(grep -oP "[^\/]+(?=\/theme.lua)" "$RC_FILE")
-    fi
-    
-    # Change theme
-    theme_set() {
-        if [[ "$HOSTNAME" == laptop ]]; then
-            theme=themelap
-        elif [[ "$HOSTNAME" == htpc ]]; then
-            theme=themehtpc
-        else
-            theme="^beautiful\.init"
-        fi
+	# Check for Beautiful library
+	BEAUTIFUL=$(grep -c 'beautiful.init' "$RC_FILE")
+	[[ "$BEAUTIFUL" -ge 1 ]] || errorout 'Could not detect theme library "beautiful". Exiting.'
 
-        if [[ "$file" ]]; then
-            [[ $(theme_list | grep -c $file) -lt 1 ]] && errorout 'No such theme.'
-            echo "changing $curtheme to $file in $RC_FILE"
-            sed -i "/$theme.*\/theme\.lua\"/s/[^/]*\(\/theme\.lua\)/$file\1/" "$RC_FILE"
-        else
-            [[ $(theme_list | grep -c $2) -lt 1 ]] && errorout 'No such theme.'
-            echo "changing $curtheme to $2 in $RC_FILE"
-            sed -i "/$theme.*\/theme\.lua\"/s/[^/]*\(\/theme\.lua\)/$2\1/" "$RC_FILE"
-        fi
-    }
-    # Print themename
-    theme_get() {
-        echo "$curtheme"
-    }
-    # Select random theme and start Xephyr instance
-    theme_random() {
-        themes=$(ls -1 $(dirname "$RC_FILE")/themes /usr/share/awesome/themes | grep -vE '/home/|/usr/|icons|README')
-        file=$(echo "$themes" | sort --random-sort | head -1)
-        theme_set
-        D=11 && start
-    }
-  
-    case "$1" in
-        g|get)    theme_get;;
-        s|set)    theme_set "${args[@]}";;
-        r|random) theme_random;;
-        *)        errorout "unrecognized argument. Use theme (list | random | get | set <theme>)";;
-    esac
+	if [[ "$HOSTNAME" == laptop ]]; then
+		curtheme=$(grep "^themelap" "$RC_FILE" | awk -F\/ '{print $2}')
+	elif [[ "$HOSTNAME" == htpc ]]; then
+		curtheme=$(grep "^themehtpc" "$RC_FILE" | awk -F\/ '{print $2}')
+	else
+		curtheme=$(grep -oP "[^\/]+(?=\/theme.lua)" "$RC_FILE")
+	fi
+
+	# Change theme
+	theme_set() {
+		if [[ "$HOSTNAME" == laptop ]]; then
+			theme=themelap
+		elif [[ "$HOSTNAME" == htpc ]]; then
+			theme=themehtpc
+		else
+			theme="^beautiful\.init"
+		fi
+
+		if [[ "$file" ]]; then
+			[[ $(theme_list | grep -c $file) -lt 1 ]] && errorout 'No such theme.'
+			echo "changing $curtheme to $file in $RC_FILE"
+			sed -i "/$theme.*\/theme\.lua\"/s/[^/]*\(\/theme\.lua\)/$file\1/" "$RC_FILE"
+		else
+			[[ $(theme_list | grep -c $2) -lt 1 ]] && errorout 'No such theme.'
+			echo "changing $curtheme to $2 in $RC_FILE"
+			sed -i "/$theme.*\/theme\.lua\"/s/[^/]*\(\/theme\.lua\)/$2\1/" "$RC_FILE"
+		fi
+	}
+	# Print themename
+	theme_get() {
+		echo "$curtheme"
+	}
+	# Select random theme and start Xephyr instance
+	theme_random() {
+		themes=$(ls -1 $(dirname "$RC_FILE")/themes /usr/share/awesome/themes | grep -vE '/home/|/usr/|icons|README')
+		file=$(echo "$themes" | sort --random-sort | head -1)
+		theme_set
+		D=11 && start
+	}
+
+	case "$1" in
+	g | get) theme_get ;;
+	s | set) theme_set "${args[@]}" ;;
+	r | random) theme_random ;;
+	*) errorout "unrecognized argument. Use theme (list | random | get | set <theme>)" ;;
+	esac
 }
 #}}}
 
 #{{{ Parse options
 parse_options() {
-    while [[ -n "$1" ]]; do
-        case "$1" in
-            start)          input=start;;
-            stop)           input=stop;;
-            restart)        input=restart;;
-            run)            input=run;;
-            theme)          input=theme;;
-            -B|--binary)    shift; AWESOME="$1";;
-            -C|--config)    shift; RC_FILE="$1";;
-            -D|--display)   shift; D="$1"
-                            [[ ! "$D" =~ ^[0-9] ]] && errorout "$D is not a valid display number";;
-            -N|--notest)    RC_FILE="$HOME"/.config/awesome/rc.lua;;
-            -S|--size)      shift; SIZE="$1";;
-            -a|--aopt)      shift; AWESOME_OPTIONS+="$1";;
-            -x|--xopts)     shift; XEPHYR_OPTIONS="$@";;
-            -h|--help)      usage;;
-            *)              args+=("$1");;
-        esac
-        shift
-    done
+	while [[ -n "$1" ]]; do
+		case "$1" in
+		start) input=start ;;
+		stop) input=stop ;;
+		restart) input=restart ;;
+		run) input=run ;;
+		theme) input=theme ;;
+		-B | --binary)
+			shift
+			AWESOME="$1"
+			;;
+		-C | --config)
+			shift
+			RC_FILE="$1"
+			;;
+		-D | --display)
+			shift
+			D="$1"
+			[[ ! "$D" =~ ^[0-9] ]] && errorout "$D is not a valid display number"
+			;;
+		-N | --notest) RC_FILE="$HOME"/.config/awesome/rc.lua ;;
+		-S | --size)
+			shift
+			SIZE="$1"
+			;;
+		-a | --aopt)
+			shift
+			AWESOME_OPTIONS+="$1"
+			;;
+		-x | --xopts)
+			shift
+			XEPHYR_OPTIONS="$@"
+			;;
+		-h | --help) usage ;;
+		*) args+=("$1") ;;
+		esac
+		shift
+	done
 }
 #}}}
 #}}}
 
-#{{{ Main 
+#{{{ Main
 main() {
-    case "$input" in
-        start)    start "${args[@]}";;
-        stop)     stop "${args[@]}";;
-        restart)  restart "${args[@]}";;
-        run)      run "${args[@]}";;
-        theme)    theme "${args[@]}";;
-        *)        echo "Option missing or not recognized";;
-    esac
+	case "$input" in
+	start) start "${args[@]}" ;;
+	stop) stop "${args[@]}" ;;
+	restart) restart "${args[@]}" ;;
+	run) run "${args[@]}" ;;
+	theme) theme "${args[@]}" ;;
+	*) echo "Option missing or not recognized" ;;
+	esac
 }
 #}}}
 
diff --git a/screen-capture b/screen-capture
--- a/screen-capture
+++ b/screen-capture
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # Values can by override
 ENCODING_LIB=${ENCODING_LIB:-libx264}
 RESOLUTION=${RESOLUTION:-1920x1080}
@@ -21,12 +20,15 @@ TESTS=${TESTS:-none}
 COPY=${COPY:-true}
 
 DS_check() {
-    type ffmpeg >/dev/null 2>&1 || { echo "ffmpeg could not be found!" >&2; exit 1; }
+	type ffmpeg >/dev/null 2>&1 || {
+		echo "ffmpeg could not be found!" >&2
+		exit 1
+	}
 }
 
 DS_help() {
-    echo "Usage: ${0##*/} --output <output file>"
-    echo "Others option:
+	echo "Usage: ${0##*/} --output <output file>"
+	echo "Others option:
     --lib libx264, libx265, huffyuv, h263p, hevc_nvenc, nvenc_h264, hevc_qsv, h264_qsv, h264_amf
     --resolution 1920x1080
     --framerate 60, 30...
@@ -39,72 +41,96 @@ DS_help() {
     --ffmpeg_arg=\"<arg 1> <arg2> ...\" additional ffmpeg arguments
     -h or --help
     -v or --version"
-    exit 0
+	exit 0
 }
 
-
 DS_main() {
-    if [[ -z $* ]]; then
-        DS_version
-        DS_help
-        exit 0
-    fi
-  
-    while [[ $# -gt 0 ]] && { [[ "$1" == "--"* ]] || [[ "$1" == "-"* ]]; } ;
-    do
-        opt="$1";
-        shift; 
-        case "$opt" in
-            "--lib" )
-            ENCODING_LIB="$1"; shift;;
-            "--ffmpeg_arg="* )     # alternate format: --first=date
-            FFMPEG_ARG="${opt#*=}";;
-            "--screen" )
-            SCREEN="$1"; shift;;
-            "--framerate" )
-            FRAMERATE="$1"; shift;;
-            "--quality" )
-            QUALITY="$1"; shift;;
-            "--preset" )
-            PRESET="$1"; shift;;
-            "--pixel" )
-            PIXEL="$1"; shift;;
-            "--resolution" )
-            RESOLUTION="$1"; shift;;
-            "--profile" )
-            PROFILE="$1"; shift;;
-            "--level" )
-            LEVEL="$1"; shift;;
-            "--output" )
-            OUTPUT="$1"; shift;;
-            "--help" | "-h" )
-            DS_help;;
-            "--version" | "-v" )
-            DS_version;;
-            "--copy" )
-            COPY=true;;
-            *) echo >&2 "Invalid option: $*"; exit 1;;
-    esac
-    done
-    DS_check
-    DS_exec
+	if [[ -z $* ]]; then
+		DS_version
+		DS_help
+		exit 0
+	fi
+
+	while [[ $# -gt 0 ]] && { [[ "$1" == "--"* ]] || [[ "$1" == "-"* ]]; }; do
+		opt="$1"
+		shift
+		case "$opt" in
+		"--lib")
+			ENCODING_LIB="$1"
+			shift
+			;;
+		"--ffmpeg_arg="*) # alternate format: --first=date
+			FFMPEG_ARG="${opt#*=}" ;;
+		"--screen")
+			SCREEN="$1"
+			shift
+			;;
+		"--framerate")
+			FRAMERATE="$1"
+			shift
+			;;
+		"--quality")
+			QUALITY="$1"
+			shift
+			;;
+		"--preset")
+			PRESET="$1"
+			shift
+			;;
+		"--pixel")
+			PIXEL="$1"
+			shift
+			;;
+		"--resolution")
+			RESOLUTION="$1"
+			shift
+			;;
+		"--profile")
+			PROFILE="$1"
+			shift
+			;;
+		"--level")
+			LEVEL="$1"
+			shift
+			;;
+		"--output")
+			OUTPUT="$1"
+			shift
+			;;
+		"--help" | "-h")
+			DS_help
+			;;
+		"--version" | "-v")
+			DS_version
+			;;
+		"--copy")
+			COPY=true
+			;;
+		*)
+			echo >&2 "Invalid option: $*"
+			exit 1
+			;;
+		esac
+	done
+	DS_check
+	DS_exec
 }
 
 DS_exec() {
-    if [[ -z "$FFMPEG_ARG" ]]; then
-        ffmpeg -f x11grab -video_size "$RESOLUTION" -framerate "$FRAMERATE" -i "$SCREEN" \
-        -vcodec "$ENCODING_LIB" -preset "$PRESET" -qp "$QUALITY" -pix_fmt "$PIXEL" \
-        -profile:v "$PROFILE" -level "$LEVEL" \
-        "$OUTPUT"
-    else
-        ffmpeg "$FFMPEG_ARG" -f x11grab -video_size "$RESOLUTION" -framerate "$FRAMERATE" -i "$SCREEN" \
-        -vcodec "$ENCODING_LIB" -preset "$PRESET" -qp "$QUALITY" -pix_fmt "$PIXEL" \
-        -profile:v "$PROFILE" -level "$LEVEL" \
-        "$OUTPUT"
-    fi
-    
+	if [[ -z "$FFMPEG_ARG" ]]; then
+		ffmpeg -f x11grab -video_size "$RESOLUTION" -framerate "$FRAMERATE" -i "$SCREEN" \
+			-vcodec "$ENCODING_LIB" -preset "$PRESET" -qp "$QUALITY" -pix_fmt "$PIXEL" \
+			-profile:v "$PROFILE" -level "$LEVEL" \
+			"$OUTPUT"
+	else
+		ffmpeg "$FFMPEG_ARG" -f x11grab -video_size "$RESOLUTION" -framerate "$FRAMERATE" -i "$SCREEN" \
+			-vcodec "$ENCODING_LIB" -preset "$PRESET" -qp "$QUALITY" -pix_fmt "$PIXEL" \
+			-profile:v "$PROFILE" -level "$LEVEL" \
+			"$OUTPUT"
+	fi
+
 }
 
 if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
-  DS_main "$@"
+	DS_main "$@"
 fi
